name: Mirror repo to Tangled

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0 # fetch full git history

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TANGLED_MIRROR_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan tangled.org >> ~/.ssh/known_hosts

      - name: Push to Tangled
        run: |
          git remote add tangled git@tangled.org:shuuji3.xyz/www
          git push tangled --all --force
          git push tangled --tags --force
